
#include "doomdef.h"
#include "r_local.h"

const skillpreset_t SkillPresets[NUMSKILLPRESETS] = {
    { "Be Gentle!",
        { .monster_counts = sk_easy,
          .player_damage = 0,
          .player_ammo = 1, } },
    { "Bring It On!",
        { .monster_counts = sk_easy,
          .player_damage = 1 } },
    { "I Own Doom!",
        { .monster_counts = sk_medium,
          .player_damage = 1 } },
    { "Watch Me Die!",
        { .monster_counts = sk_hard,
          .player_damage = 1 } },
    { "Hardcore!",
        { .monster_counts = sk_hard,
          .player_damage = 1,
          .player_ammo = 1,
          .monster_speed = 1 } },
    {"Be Merciless!",
        { .monster_counts = sk_hard,
          .player_damage = 1,
          .player_ammo = 2,
          .monster_speed = 2,
          .monster_shrink = 1,
          .monster_reduced_pain = 1,
          .monster_random_aim = 1, } },
    { "Nightmare!",
        { .monster_counts = sk_hard,
          .player_damage = 1,
          .player_ammo = 1,
          .monster_speed = 1,
          .monster_respawns = 1,
          .monster_reactions = 1, } },
    { "Ultra-Nightmare!",
        { .monster_counts = sk_hard,
          .player_damage = 1,
          .player_ammo = 1,
          .monster_speed = 1,
          .monster_reactions = 1,
          .monster_respawns = 1,
          .permadeath = 1, } },
    { "Impossible!",
        { .monster_counts = sk_hard,
          .player_damage = 3,
          .player_ammo = 1,
          .monster_speed = 2,
          .monster_shrink = 1,
          .monster_reduced_pain = 1,
          .monster_respawns = 1,
          .monster_random_aim = 1,
          .monster_reactions = 1,
          .permadeath = 1,
          .pistol_start = 1 } },
};

const gamesettingspreset_t SettingsPresets[] = {
    { // Modern
        {
            .MotionBob = 0x100000,
            .Brightness = 125,
            .VideoFilters[filt_sprites] = 1,
            .FlashBrightness = 32,
            .StoryText = true,
            .MapStats = true,
            .EnableMessages = true,
            .HudOpacity = 128,
            .HudMargin = 19,
            .HudTextColors = true,
            .SfxVolume = 80,
            .MusVolume = 80,
        },
        {
            .BitDepth = BITDEPTH_32,
        },
        {
            .crosshair = 2,
            .verticallook = -1,
            .autorun = true,
            .movesensitivity = 50,
            .looksensitivity = 50,
            .hue = 84, .saturation = 159, .value = 52,
        }
    },
    { // Vanilla
        {
            .MotionBob = 0x100000,
            .FlashBrightness = 32,
            .EnableMessages = true,
            .HudOpacity = 128,
            .HudMargin = 19,
            .SfxVolume = 80,
            .MusVolume = 80,
        },
        {
            .BitDepth = BITDEPTH_32,
            .NoGammaCorrect = true,
        },
        {
            .verticallook = -1,
            .autoaim = true,
            .movesensitivity = 50,
            .looksensitivity = 50,
            .hue = 84, .saturation = 159, .value = 52,
        }
    },
    { // Merciless
        {
            .MotionBob = 0x100000,
            .Brightness = 100,
            .FlashBrightness = 32,
            .StoryText = true,
            .EnableMessages = true,
            .HudOpacity = 128,
            .HudMargin = 15,
            .HudTextColors = true,
            .SfxVolume = 100,
            .MusVolume = 80,
        },
        {
            .BitDepth = BITDEPTH_32,
        },
        {
            .verticallook = -1,
            .autoaim = true,
            .movesensitivity = 50,
            .looksensitivity = 50,
            .hue = 84, .saturation = 159, .value = 52,
        }
    },
    { // Retro
        {
            .MotionBob = 0x100000,
            .Brightness = 200,
            .FlashBrightness = 32,
            .VideoFilters[filt_skies] = 1,
            .StoryText = true,
            .MapStats = true,
            .EnableMessages = true,
            .HudOpacity = 196,
            .HudMargin = 5,
            .HudTextColors = true,
            .ColorDither = 2,
            .SfxVolume = 100,
            .MusVolume = 80,
        },
        {
            .BitDepth = BITDEPTH_32,
        },
        {
            .crosshair = 2,
            .verticallook = 1,
            .autorun = true,
            .movesensitivity = 50,
            .looksensitivity = 50,
            .hue = 84, .saturation = 159, .value = 52,
        }
    },
    { // Accessible
        {
            .MotionBob = 0,
            .Brightness = 200,
            .StoryText = true,
            .MapStats = true,
            .EnableMessages = true,
            .HudOpacity = 255,
            .HudMargin = 15,
            .HudTextColors = true,
            .ColorDither = 2,
            .SfxVolume = 100,
            .MusVolume = 80,
        },
        {
            .BitDepth = BITDEPTH_32,
        },
        {
            .crosshair = 2,
            .verticallook = 1,
            .autorun = true,
            .autoaim = true,
            .movesensitivity = 50,
            .looksensitivity = 50,
            .hue = 84, .saturation = 159, .value = 52,
        }
    },
};

const controlpreset_t ControllerPresets[MAXCONTROLSETUPS] ALIGNED(16) = {
    {
        .name = "Modern",
        .ctrl = {
            .buttons = {
                [BT_RIGHT]          = PAD_RIGHT_C,
                [BT_LEFT]           = PAD_LEFT_C,
                [BT_FORWARD]        = 0,
                [BT_BACK]           = 0,
                [BT_ATTACK]         = PAD_Z_TRIG,
                [BT_USE]            = PAD_B,
                [BT_MAP]            = PAD_L_TRIG,
                [BT_SPEED]          = 0,
                [BT_STRAFE]         = 0,
                [BT_STRAFELEFT]     = 0,
                [BT_STRAFERIGHT]    = 0,
                [BT_WEAPONBACKWARD] = PAD_DOWN,
                [BT_WEAPONFORWARD]  = PAD_RIGHT,
                [BT_LOOK]           = 0,
                [BT_LOOKUP]         = PAD_UP_C,
                [BT_LOOKDOWN]       = PAD_DOWN_C,
                [BT_JUMP]           = PAD_A,
                [BT_CROUCH]         = PAD_R_TRIG,
            },
            .stick = STICK_MOVE | STICK_STRAFE
        },
        .ctrl2 = {
            .a = BT_WEAPONFORWARD,
            .b = BT_CROUCH,
            .z = BT_JUMP,
            .stick = STICK_TURN | STICK_VLOOK
        },
    },

    {
        .name = "Classic",
        .ctrl = {
            .buttons = {
                [BT_RIGHT]          = PAD_RIGHT,
                [BT_LEFT]           = PAD_LEFT,
                [BT_FORWARD]        = PAD_UP,
                [BT_BACK]           = PAD_DOWN,
                [BT_ATTACK]         = PAD_Z_TRIG,
                [BT_USE]            = PAD_RIGHT_C,
                [BT_MAP]            = PAD_UP_C,
                [BT_SPEED]          = PAD_LEFT_C,
                [BT_STRAFE]         = PAD_DOWN_C,
                [BT_STRAFELEFT]     = PAD_L_TRIG,
                [BT_STRAFERIGHT]    = PAD_R_TRIG,
                [BT_WEAPONBACKWARD] = PAD_A,
                [BT_WEAPONFORWARD]  = PAD_B,
                [BT_LOOK]           = 0,
                [BT_LOOKUP]         = 0,
                [BT_LOOKDOWN]       = 0,
                [BT_JUMP]           = 0,
                [BT_CROUCH]         = 0,
            },
            .stick = STICK_MOVE | STICK_TURN
        },
        .ctrl2 = {
            .a = BT_USE,
            .b = BT_MAP,
            .z = BT_SPEED,
            .stick = STICK_STRAFE,
        },
    },

    {
        .name = "Arcade",
        .ctrl = {
            .buttons = {
                [BT_RIGHT]          = 0,
                [BT_LEFT]           = 0,
                [BT_FORWARD]        = PAD_UP_C,
                [BT_BACK]           = PAD_DOWN_C,
                [BT_ATTACK]         = PAD_Z_TRIG,
                [BT_USE]            = PAD_R_TRIG,
                [BT_MAP]            = PAD_L_TRIG,
                [BT_SPEED]          = 0,
                [BT_STRAFE]         = 0,
                [BT_STRAFELEFT]     = PAD_LEFT_C,
                [BT_STRAFERIGHT]    = PAD_RIGHT_C,
                [BT_WEAPONBACKWARD] = PAD_A,
                [BT_WEAPONFORWARD]  = PAD_B,
                [BT_LOOK]           = 0,
                [BT_LOOKUP]         = 0,
                [BT_LOOKDOWN]       = 0,
                [BT_JUMP]           = PAD_UP,
                [BT_CROUCH]         = PAD_DOWN,
            },
            .stick = STICK_VLOOK | STICK_TURN
        },
        .ctrl2 = {
            .a = BT_ATTACK,
            .b = BT_USE,
            .z = BT_SPEED,
            .stick = STICK_MOVE | STICK_STRAFE,
        },
    },

    {
        .name = "Dark",
        .ctrl = {
            .buttons = {
                [BT_RIGHT]          = 0,
                [BT_LEFT]           = 0,
                [BT_FORWARD]        = 0,
                [BT_BACK]           = 0,
                [BT_ATTACK]         = PAD_Z_TRIG,
                [BT_USE]            = PAD_B,
                [BT_MAP]            = PAD_L_TRIG,
                [BT_SPEED]          = 0,
                [BT_STRAFE]         = 0,
                [BT_STRAFELEFT]     = PAD_LEFT_C,
                [BT_STRAFERIGHT]    = PAD_RIGHT_C,
                [BT_WEAPONBACKWARD] = 0,
                [BT_WEAPONFORWARD]  = PAD_A,
                [BT_LOOK]           = PAD_R_TRIG,
                [BT_LOOKUP]         = PAD_UP_C,
                [BT_LOOKDOWN]       = PAD_DOWN_C,
                [BT_JUMP]           = PAD_UP,
                [BT_CROUCH]         = PAD_DOWN,
            },
            .stick = STICK_MOVE | STICK_TURN
        },
        .ctrl2 = {
            .a = BT_WEAPONFORWARD,
            .b = BT_USE,
            .z = BT_LOOK,
            .stick = STICK_VLOOK | STICK_STRAFE,
        },
    },

    {
        .name = "Hunter",
        .ctrl = {
            .buttons = {
                [BT_RIGHT]          = 0,
                [BT_LEFT]           = 0,
                [BT_FORWARD]        = PAD_UP_C,
                [BT_BACK]           = PAD_DOWN_C,
                [BT_ATTACK]         = PAD_Z_TRIG,
                [BT_USE]            = PAD_RIGHT,
                [BT_MAP]            = PAD_L_TRIG,
                [BT_SPEED]          = 0,
                [BT_STRAFE]         = 0,
                [BT_STRAFELEFT]     = PAD_LEFT_C,
                [BT_STRAFERIGHT]    = PAD_RIGHT_C,
                [BT_WEAPONBACKWARD] = PAD_B,
                [BT_WEAPONFORWARD]  = PAD_A,
                [BT_LOOK]           = 0,
                [BT_LOOKUP]         = 0,
                [BT_LOOKDOWN]       = 0,
                [BT_JUMP]           = PAD_R_TRIG,
                [BT_CROUCH]         = PAD_DOWN,
            },
            STICK_VLOOK | STICK_TURN
        },
        .ctrl2 = {
            .a = BT_JUMP,
            .b = BT_USE,
            .z = BT_LOOK,
            .stick = STICK_MOVE | STICK_STRAFE,
        },
    },

    {
        .name = "Action",
        .ctrl = {
            .buttons = {
                [BT_RIGHT]          = 0,
                [BT_LEFT]           = 0,
                [BT_FORWARD]        = 0,
                [BT_BACK]           = 0,
                [BT_ATTACK]         = PAD_Z_TRIG,
                [BT_USE]            = PAD_R_TRIG,
                [BT_MAP]            = PAD_L_TRIG,
                [BT_SPEED]          = 0,
                [BT_STRAFE]         = 0,
                [BT_STRAFELEFT]     = PAD_LEFT_C,
                [BT_STRAFERIGHT]    = PAD_RIGHT_C,
                [BT_WEAPONBACKWARD] = PAD_B,
                [BT_WEAPONFORWARD]  = PAD_A,
                [BT_LOOK]           = 0,
                [BT_LOOKUP]         = PAD_UP,
                [BT_LOOKDOWN]       = PAD_DOWN,
                [BT_JUMP]           = PAD_UP_C,
                [BT_CROUCH]         = PAD_DOWN_C,
            },
            .stick = STICK_MOVE | STICK_TURN
        },
        .ctrl2 = {
            .a = BT_JUMP,
            .b = BT_USE,
            .z = BT_LOOK,
            .stick = STICK_STRAFE | STICK_VLOOK,
        },
    },

    {
        .name = "Nuke",
        .ctrl = {
            .buttons = {
                [BT_RIGHT]          = 0,
                [BT_LEFT]           = 0,
                [BT_FORWARD]        = PAD_UP_C,
                [BT_BACK]           = PAD_DOWN_C,
                [BT_ATTACK]         = PAD_Z_TRIG,
                [BT_USE]            = PAD_A,
                [BT_MAP]            = PAD_L_TRIG,
                [BT_SPEED]          = 0,
                [BT_STRAFE]         = 0,
                [BT_STRAFELEFT]     = PAD_LEFT_C,
                [BT_STRAFERIGHT]    = PAD_RIGHT_C,
                [BT_WEAPONBACKWARD] = PAD_LEFT,
                [BT_WEAPONFORWARD]  = PAD_RIGHT,
                [BT_LOOK]           = 0,
                [BT_LOOKUP]         = 0,
                [BT_LOOKDOWN]       = 0,
                [BT_JUMP]           = PAD_R_TRIG,
                [BT_CROUCH]         = PAD_B,
            },
            .stick = STICK_VLOOK | STICK_TURN
        },
        .ctrl2 = {
            .a = BT_JUMP,
            .b = BT_WEAPONFORWARD,
            .z = BT_STRAFE,
            .stick = STICK_STRAFE | STICK_MOVE,
        },
    },

    {
        .name = "Fighter",
        .ctrl = {
            .buttons = {
                [BT_RIGHT]          = PAD_RIGHT,
                [BT_LEFT]           = PAD_LEFT,
                [BT_FORWARD]        = PAD_UP_C,
                [BT_BACK]           = PAD_DOWN_C,
                [BT_ATTACK]         = PAD_Z_TRIG,
                [BT_USE]            = PAD_B,
                [BT_MAP]            = PAD_A,
                [BT_SPEED]          = 0,
                [BT_STRAFE]         = 0,
                [BT_STRAFELEFT]     = PAD_LEFT_C,
                [BT_STRAFERIGHT]    = PAD_RIGHT_C,
                [BT_WEAPONBACKWARD] = PAD_L_TRIG,
                [BT_WEAPONFORWARD]  = PAD_R_TRIG,
                [BT_LOOK]           = 0,
                [BT_LOOKUP]         = 0,
                [BT_LOOKDOWN]       = 0,
                [BT_JUMP]           = PAD_UP,
                [BT_CROUCH]         = PAD_DOWN,
            },
            .stick = STICK_TURN | STICK_VLOOK
        },
        .ctrl2 = {
            .a = BT_WEAPONFORWARD,
            .b = BT_JUMP,
            .z = BT_CROUCH,
            .stick = STICK_STRAFE | STICK_MOVE,
        },
    }
};
